services:
  thanks-fes-web:
    build:
      context: ./thanks-fes-web
      args:
        BACKEND_API_SERVER: ${BACKEND_API_SERVER}
    image: thanks-fes-web
    container_name: thanks-fes-web
    command: /bin/sh -c "envsubst '$$BACKEND_API_SERVER' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      BACKEND_API_SERVER: ${BACKEND_API_SERVER}
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
    ports:
      - 80:80
    tty: true

  thanks-fes-api:
    build: ./thanks-fes-api
    image: thanks-fes-api
    container_name: thanks-fes-api
    volumes:
      - ./thanks-fes-api/app:/src/app
    env_file:
      - .env
    ports:
      - 8888:8888
    networks:
      - thanks-fes-network

  thanks-fes-db:
    build: ./thanks-fes-db
    image: thanks-fes-db
    container_name: thanks-fes-db
    env_file:
      - .env
    ports:
      - 50000:50000
    networks:
      - thanks-fes-network

networks:
  thanks-fes-network:
    driver: bridge
