services:
  thanks-fes-web:
    build:
      context: ./thanks-fes-web
    image: thanks-fes-web
    container_name: thanks-fes-web
    ports:
      - 80:80
    tty: true
    networks:
      - thanks-fes-network

  thanks-fes-api:
    build:
      context: ./thanks-fes-api
      args:
        - APP_MODE=prod
    image: thanks-fes-api
    container_name: thanks-fes-api
    volumes:
      - ./thanks-fes-api/app:/src/app
    env_file:
      - .env
    ports:
      - 8888:8888
    networks:
      - thanks-fes-network

  thanks-fes-db:
    build: ./thanks-fes-db
    image: thanks-fes-db
    container_name: thanks-fes-db
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - thanks-fes-network

networks:
  thanks-fes-network:
    driver: bridge
